stages:
  prepare:
    foreach: ${targets}
    do:
      cmd: >
        python scripts/prepare_features.py
        --raw-data-path ${paths.raw_data}
        --datetime-column ${data.datetime_column}
        --fillna-method ${data.fillna_method}
        --tabular-covariate-columns ${data.tabular_covariate_columns}
        --time-components ${data.time_components}
        --target-name ${item.name}
        --y-column ${item.y_column}
        --prediction-horizon ${item.prediction_horizon}
        --lag-columns ${item.lag_columns}
        --output-dir ${paths.data_interim}/${item.name}
        --data-format ${data.data_format}
        --log-level ${log_level}
        --log-file ${log_file}
      deps:
      - scripts/prepare_features.py
      - src/dcp_nf_forecast/
      - ${paths.raw_data}
      params:
      - paths.raw_data
      - paths.data_interim
      - data.datetime_column
      - data.fillna_method
      - data.tabular_covariate_columns
      - data.data_format
      - data.time_components
      - targets
      - log_level
      - log_file
      outs:
      - data/interim/${item.name}/X.feather
      - data/interim/${item.name}/y.feather

  split:
    foreach: ${targets}
    do:
      cmd: >
        python scripts/split_data.py
        --input-dir ${paths.data_interim}/${item.name}
        --output-dir ${paths.data_processed}/${item.name}
        --train-ratio ${splits.train}
        --val-ratio ${splits.val}
        --test-ratio ${splits.test}
        --data-format ${data.data_format}
        --log-level ${log_level}
        --log-file ${log_file}
      deps:
      - scripts/split_data.py
      - src/dcp_nf_forecast/
      - data/interim/${item.name}/
      params:
      - paths.data_interim
      - paths.data_processed
      - data.data_format
      - splits
      - log_level
      - log_file
      outs:
      - data/processed/${item.name}/X_train.feather
      - data/processed/${item.name}/y_train.feather
      - data/processed/${item.name}/X_val.feather
      - data/processed/${item.name}/y_val.feather
      - data/processed/${item.name}/X_test.feather
      - data/processed/${item.name}/y_test.feather
