log_level: info
log_file: logs/pipeline.log
seed: 42
test_mode: true

paths:
  raw_data: ../dcp/norm_data/norm_fondium_15_min_data_2023.csv
  data_interim: data/interim
  data_processed: data/processed

data:
  datetime_column: new_time
  data_format: feather
  fillna_method: ffill
  tabular_covariate_columns: none
  time_components: time,day_of_week,day_of_year

eval:
  n_samples: 1000

splits:
  train: 0.80
  val: 0.10
  test: 0.10

targets:
- name: dla
  y_column: dla_stromverbrauch_kwh
  prediction_horizon: 12
  lag_columns: dla_stromverbrauch_kwh:96
- name: ofen_g_koks
  y_column: ofen_g_koks_kg
  prediction_horizon: 12
  lag_columns: ofen_g_koks_kg:96
- name: ofen_f_koks
  y_column: ofen_f_koks_kg
  prediction_horizon: 12
  lag_columns: ofen_f_koks_kg:96
- name: pl2
  y_column: pl2_stromverbrauch_kwh
  prediction_horizon: 12
  lag_columns: pl2_stromverbrauch_kwh:96
