[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61", "setuptools_scm>=7"]

[project]
dependencies = [
  "numpy>=1.26",
  "pandas>=2.0",
  "pyyaml>=6.0",
  "hybrid-flows @ git+https://github.com/MArpogaus/hybrid-flows.git@v0.1.0",
  "tensorflow>=2.15",
  "tensorflow-probability>=0.23",
  "pyarrow==23.*",
  "mlflow>=3,<4"
]
description = "Forecasting with multivariate normalizing flows"
dynamic = ["version"]
name = "dcp-nf-forecast"
requires-python = ">=3.11"

[project.optional-dependencies]
cuda = [
  'dcp-nf-forecast[train]',
  'tensorflow[and-cuda]'
]
dev = [
  "commitizen",
  "mypy",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "pytest-xdist",
  "python-lsp-ruff",
  "python-lsp-server",
  "ruff"
]
train = [
  "dvc[webdav,ssh]==3.*"
]

[tool.commitizen]
major_version_zero = true
name = "cz_conventional_commits"
tag_format = "v$version"
update_changelog_on_bump = true
version_provider = "scm"
version_scheme = "pep440"

[tool.coverage.report]
fail_under = 90
show_missing = true

[tool.coverage.run]
branch = true
omit = ["test/*", "scripts/*"]
source = ["src/dcp_nf_forecast"]

[tool.pytest.ini_options]
addopts = ["-v", "--tb=short", "-n", "auto", "--dist=loadfile"]
markers = ["slow", "integration"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
testpaths = ["test"]

[tool.ruff]
indent-width = 4
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["I", "E", "F", "UP"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
# https://stackoverflow.com/a/74404703
# omits local version, useful because pypi does not support it
local_scheme = "no-local-version"
