compile_kwargs: {}
fit_kwargs:
  batch_size: 256
  early_stopping_patience: 20
  epochs: 400
  learning_rate: 0.0005
  verbose: true
model_kwargs:
  base_distribution_kwargs:
    distribution_name: normal
  distribution: masked_autoregressive_flow
  nested_bijectors:
  - bijector: Scale
    parameters_constraint_fn: tensorflow.math.softplus
    parameters_fn: parameter_vector_or_simple_network
    parameters_fn_kwargs:
      activation: relu
      batch_norm: false
      conditional: true
      dropout: 0
      hidden_units:
      - 256
      - 256
      parameter_shape:
      - 48
    parameters_slice_size: 1
  - bijector: BernsteinPolynomial
    bijector_kwargs:
      domain:
      - 0.0
      - 1.0
      extrapolation: false
    invert: true
    parameters_constraint_fn: hybrid_flows.activations.get_thetas_constrain_fn
    parameters_constraint_fn_kwargs:
      allow_flexible_bounds: false
      bounds: none
      high: 5.0
      low: -5.0
    parameters_fn: parameter_vector_or_simple_network
    parameters_fn_kwargs:
      activation: relu
      batch_norm: false
      conditional: true
      dropout: 0
      hidden_units:
      - 256
      - 256
      parameter_shape:
      - 48
      - 12
    parameters_slice_size: 12
  num_layers: 1
  num_parameters: 13
  parameters_fn_kwargs:
    activation: relu
    hidden_units:
    - 256
    - 256
