compile_kwargs:
  jit_compile: false
fit_kwargs:
  batch_size: 256
  early_stopping_patience: 20
  epochs: 400
  learning_rate: 0.001
  verbose: true
model_kwargs:
  distribution: multivariate_truncated_normal
  parameters_fn_kwargs:
    activation: relu
    batch_norm: false
    conditional: true
    dropout: 0
    hidden_units:
    - 256
    - 256
  high: 5.0
  low: 0.0
