compile_kwargs: {}
fit_kwargs:
  batch_size: 256
  early_stopping_patience: 10
  epochs: 10
  learning_rate: 0.001
  verbose: true
model_kwargs:
  distribution: masked_autoregressive_flow
  num_layers: 1
  bijector: BernsteinPolynomial
  bijector_kwargs:
    domain: [0, 1]
    extrapolation: false
  invert: true
  base_distribution_kwargs:
    distribution_name: lognormal
  num_parameters: 96
  parameters_constraint_fn: hybrid_flows.activations.get_thetas_constrain_fn
  parameters_constraint_fn_kwargs:
    allow_flexible_bounds: false
    bounds: none
    low: 0.007
    high: 148
  parameters_fn_kwargs:
    activation: relu
    hidden_units: [256, 256, 256]
    conditional: true
