compile_kwargs: {}
fit_kwargs:
  batch_size: 256
  early_stopping_patience: 20
  epochs: 400
  learning_rate: 0.0005
  max_epochs: 400
  verbose: true
model_kwargs:
  base_distribution_kwargs:
    distribution_name: truncated_normal
    low: 0.0
    high: 5.0
  bijector: RationalQuadraticSpline
  bijector_kwargs:
    range_min: 0
  distribution: masked_autoregressive_flow
  num_layers: 1
  num_parameters: 35
  parameters_constraint_fn: hybrid_flows.activations.get_spline_param_constrain_fn
  parameters_constraint_fn_kwargs:
    interval_width: 5
    min_bin_width: 0.001
    min_slope: 0.001
    nbins: 12
  parameters_fn_kwargs:
    activation: relu
    conditional: true
    hidden_units:
    - 256
    - 256
