compile_kwargs: {}
fit_kwargs:
  batch_size: 256
  early_stopping_patience: 20
  epochs: 400
  learning_rate: 0.0005
  verbose: true
model_kwargs:
  base_distribution_kwargs:
    distribution_name: normal
  bijector: BernsteinPolynomial
  bijector_kwargs:
    domain:
    - 0.0
    - 1.0
    extrapolation: false
  distribution: masked_autoregressive_flow
  invert: true
  num_layers: 1
  num_parameters: 8
  parameters_constraint_fn: hybrid_flows.activations.get_thetas_constrain_fn
  parameters_constraint_fn_kwargs:
    allow_flexible_bounds: false
    bounds: none
    high: 5.0
    low: -5.0
  parameters_fn_kwargs:
    activation: relu
    conditional: true
    hidden_units:
    - 256
    - 256
