compile_kwargs:
  jit_compile: false
fit_kwargs:
  batch_size: 256
  early_stopping_patience: 10
  epochs: 100
  learning_rate: 0.0005
  verbose: true
model_kwargs:
  distribution: multivariate_normal_diag
  parameters_fn_kwargs:
    activation: relu
    batch_norm: false
    conditional: true
    dropout: 0
    hidden_units:
    - 32
    - 32
